In [28]:
import cv2
import numpy as np

In [30]:

os.getcwd()



image = np.array(Image.open('sample images/sample_image3.jpg')) 

#imshow(image,cmap=matplotlib.pyplot.get_cmap('grey'))
impr = image_processing()
image = impr.rgb_to_greyscale(image)

display(image)


NameError: name 'Image' is not defined

In [31]:
im = [[0,0,1,0,0,0,1,0,1],[0,0,0,1,0,0,1,0,1],[1,0,1,1,0,1,0,0,1],[1,0,1,0,0,1,0,0,1],[1,0,0,0,1,0,1,0,1],[0,1,0,1,0,0,0,1,0],[0,0,1,0,0,1,0,0,0]]
t1 = 0.5
t2 = 0.5
im = np.array(im)

In [32]:
f = cv2.Canny(im,t1,t2,apertureSize = 3)

error: C:\builds\master_PackSlaveAddon-win64-vc12-static\opencv\modules\imgproc\src\canny.cpp:587: error: (-215) depth == CV_8U in function cv::Canny


In [33]:
def print_(im):
    for row in im:
        print(row)

In [34]:
print_(im)

[0 0 1 0 0 0 1 0 1]
[0 0 0 1 0 0 1 0 1]
[1 0 1 1 0 1 0 0 1]
[1 0 1 0 0 1 0 0 1]
[1 0 0 0 1 0 1 0 1]
[0 1 0 1 0 0 0 1 0]
[0 0 1 0 0 1 0 0 0]


In [35]:
def divide_by(im,)

SyntaxError: invalid syntax (<ipython-input-35-c8e266c42e09>, line 1)

In [36]:
lines = [[1,2],[3,4],[5,6],[7,8]]

In [37]:
lines[0]

[1, 2]

In [38]:
lines = ["ekta","ic_garam"]

In [39]:
lines[0]

'ekta'

In [26]:
lines[1]

[3, 4]

In [41]:
import sys
osx = sys.platform
import os
if(osx == "win32"):
    os.chdir('C:\Users\dhrre\Desktop\Projects\Handwriting_recognition_using_neural_nets_on_FPGA\Image processing')
else:
    print("OSX ERROR")
    
import cv2
import numpy as np

img = cv2.imread('sample_image.jpg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray,50,150,apertureSize = 3)
minLineLength = 100
maxLineGap = 10
lines = cv2.HoughLinesP(edges,1,np.pi/180,100,minLineLength,maxLineGap)
for x1,y1,x2,y2 in lines[0]:
    cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)

cv2.imwrite('houghlines5.jpg',img)


error: C:\builds\master_PackSlaveAddon-win64-vc12-static\opencv\modules\imgproc\src\color.cpp:7564: error: (-215) scn == 3 || scn == 4 in function cv::cvtColor
